# Generated by Django 5.2.5 on 2026-02-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient_latitude_patient_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='time_to_take',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='medicine_details',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
            preserve_default=False,
        ),
    ]
